'use client';

import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f9f9f9] text-[#1a1c1c] flex flex-col font-sans">
      {/* Header */}
      <header className="bg-[#f9f9f9]/80 backdrop-blur-md text-[#000000] sticky top-0 z-40 border-b border-[#e2e2e2]">
        <div className="flex justify-between items-center px-6 py-4 max-w-6xl mx-auto w-full">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <span className="material-symbols-outlined text-[#000000] text-2xl font-bold">real_estate_agent</span>
            <span className="text-xl font-bold tracking-tight">RentSafe</span>
          </Link>
          <Link href="/" className="text-xs font-bold text-black border border-black px-4 py-2 rounded-xl hover:bg-[#000000] hover:text-white transition-all">
            Back to Home
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-grow max-w-3xl mx-auto px-6 py-16 w-full">
        <h1 className="text-3xl font-black tracking-tight text-[#000000] mb-2">Terms of Service</h1>
        <p className="text-xs text-[#585f6c] mb-8 font-semibold uppercase tracking-wider">Last updated: July 28, 2026</p>

        {/* Testnet Disclaimer Alert Box */}
        <div className="bg-[#fff4e5] border-l-4 border-[#ffa117] p-5 rounded-r-xl mb-10 text-sm text-[#663c00] space-y-2">
          <div className="flex items-center gap-2 font-bold text-[#b26a00]">
            <span className="material-symbols-outlined text-lg">warning</span>
            <span>TESTNET DEMO APPLICATION DISCLAIMER</span>
          </div>
          <p className="text-xs leading-relaxed">
            RentSafe is currently a <strong>Testnet Demonstration Application</strong>. It is designed for trial and evaluation purposes only. No real-world financial assets (including real XLM, USDC, or fiat currency) are custodied, processed, or transferred. All wallet operations occur exclusively on the Stellar Testnet.
          </p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed text-[#333538]">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-black">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the RentSafe testnet application, you acknowledge that this is a simulated interface running entirely on test networks. You agree to use this site solely for testing and evaluation.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-black">2. Simulated Assets & Testnet Tokens</h2>
            <p>
              All interactions, contract lockups, and releases are processed using <strong>Testnet Lumens (XLM)</strong>. These tokens hold absolutely zero real-world value and cannot be redeemed for legal tender. Under no circumstances should you attempt to send real mainnet assets to any addresses generated by or displayed on this application.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-black">3. No Financial Custody or Liability</h2>
            <p>
              RentSafe does not act as a custodian, bank, or escrow agent. All locked funds are held directly inside Soroban smart contract addresses on the decentralized Stellar Testnet. The software is provided "AS IS" without warranties of any kind. We assume no liability for smart contract failures, browser wallet incompatibilities, or loss of testnet credentials.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-black">4. Prohibited Uses</h2>
            <p>
              You agree not to use the testnet application to transmit spam, execute malicious attacks on the Stellar Testnet, or simulate fraudulent agreements. We reserve the right to suspend or block access to the interface for address spaces violating these guidelines.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-black">5. Modification of Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Your continued use of the application following the posting of changes constitutes acceptance of those changes.
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-[#f3f3f3] text-[#000000] border-t border-[#e2e2e2] mt-12">
        <div className="px-6 py-8 max-w-6xl mx-auto w-full text-center md:text-left md:flex justify-between items-center text-xs text-[#585f6c]">
          <p>© 2026 RentSafe. Testnet Demonstration Platform.</p>
          <div className="flex gap-4 justify-center mt-4 md:mt-0 font-bold">
            <Link href="/" className="hover:underline text-black">Home</Link>
            <Link href="/privacy" className="hover:underline text-black">Privacy Policy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
